# -*- coding: utf-8 -*-
"""Track A: 49 `office` aggregate creates. **DROPPED on 2026-09-11 - will not run.**

This emitter is kept as the working behind a decision, not as a tool. Two things
changed on 2026-09-11:

* A separate import had already entered the salt-administration **post titles**
  into `OFFICE_CODES`. Running this would propose 49 more office codes on top.
* Ning Hao's list names the **institutions** (都轉運鹽使司 and its 分司), not the
  posts held in them. An institution with a 治所 and a parent is a place, which is
  where he proposed putting it in the first place. It now goes to `ADDR_CODES` and
  `ADDR_BELONGS_DATA` through `tools/salt-admin/emit_addresses.py`.

So `main()` refuses. `build_batch()` is left importable because the tests around it
still document what Track A would have written -
but nothing here produces a file any more, and `OFFICE_CODES` has no delete path
(API.md 13.3), so an accidental run would not be undoable.

See `docs/11-salt-administration-design.md`, header and §5.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError as exc:  # pragma: no cover - environment-dependent
    raise ImportError("PyYAML is required (see requirements.txt)") from exc


# Must match build_dataset.py's `schema_version`. Checked rather than assumed: a
# stale dataset otherwise fails with a bare KeyError on a field that moved.
DATASET_SCHEMA = 2

HEADER = """\
# Ming/Qing salt administration - Track A (OFFICE_CODES via the `office` aggregate).
#
# Generated by tools/salt-admin/emit_staging.py from {dataset}.
# Design: docs/11-salt-administration-design.md
#
# {n} creates. Every one writes GLOBAL reference data (AGENTS.md rule 12): visible
# to every CBDB user and referenced by any number of person records.
#
# HISTORICAL. Track A was dropped on 2026-09-11 and this emitter refuses to run.
# The address rows it refers to below now go through the API - see
# tools/salt-admin/emit_addresses.py.
"""


def proposal_for(unit: dict) -> dict:
    """One staging proposal. Field order is chosen for reading, not for the parser."""
    o = unit["office"]
    seats = "；".join(f"{a['seat']['raw']} {a['first']}–{a['last']}"
                     for a in unit["addresses"])
    return {
        "id": _proposal_id(unit),
        "resource": "office",   # NEVER `offices` - that alias resolves to postings
        "operation": "create",
        "person_id": 0,         # convention for global reference data (API.md 13)
        # No target_pk: c_office_id is server-assigned. staging.py rejects a
        # target_pk carrying a server-assigned field on create - but note `{}` slips
        # through, so the key is omitted rather than emptied.
        "changes": {
            "name": o["name"],
            "name_alt": o["name_alt"],
            "translation": o["translation"],
            "translation_alt": o["translation_alt"],
            "pinyin": o["pinyin"],
            "pinyin_alt": o["pinyin_alt"],
            "dynasty_code": o["dynasty_code"],
            "type_ids": list(o["type_ids"]),
            "source_id": o["source_id"],
            "pages": o["pages"],
            "notes": o["notes"],
        },
        "source_quote": f"{unit['dynasty']}｜{unit['name_short']}｜治所 {seats}",
        "confidence": "high",
    }


def _proposal_id(unit: dict) -> str:
    dyn = "ming" if unit["dynasty"] == "明代" else "qing"
    kind = "ys" if unit["kind"] == "運司" else "fs"
    return f"off-{dyn}-{kind}-{unit['region']}-{unit['name_short']}"


def build_batch(dataset: dict, batch_id: str) -> dict:
    units = [u for u in dataset["units"] if u["emitted"]]
    excluded = [u for u in dataset["units"] if not u["emitted"]]
    lines = [
        f"{dataset['stats']['office_creates']} office codes for the Ming and Qing "
        f"salt administration, from {dataset['source']['xlsx']} (Ning Hao).",
        "",
        "Each unit is also proposed as an ADDR_CODES place name, which /api/v2 cannot "
        "create - that half ships as data/salt-admin/track_b_load.sql. See "
        "docs/11-salt-administration-design.md.",
    ]
    if excluded:
        lines += ["", "Excluded pending a decision from Ning Hao:"]
        lines += [f"  - {u['dynasty']} {u['name_short']}: {u['blocked_reason'] or 'blocker finding'}"
                  for u in excluded]
    return {
        "batch_id": batch_id,
        "source_excerpt": "\n".join(lines),
        "proposals": [proposal_for(u) for u in units],
    }


DROPPED = (
    "Track A was dropped on 2026-09-11: a separate import had already covered the "
    "salt-administration post titles, and Ning Hao's list names the INSTITUTIONS, "
    "which belong in the place-name tables. This emitter no longer produces a "
    "batch - OFFICE_CODES has no delete path, so 49 accidental office creates "
    "could not be undone.\n"
    "What to run instead:\n"
    "  python tools/salt-admin/emit_addresses.py --batch-id <id>"
)


def main(argv=None) -> int:
    print("error: " + DROPPED, file=sys.stderr)
    return 1


def _superseded_main(argv=None) -> int:
    """The body as it stood on 2026-09-10, unreachable. Kept so the decision can be
    read against what it replaced rather than against an empty function."""
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dataset", type=Path, default=Path("data/salt-admin/dataset.json"))
    ap.add_argument("--batch-id", required=True)
    ap.add_argument("--staging-root", type=Path, default=Path("data/staging"))
    args = ap.parse_args(argv)

    if not args.dataset.exists():
        print(f"error: {args.dataset} not found - run build_dataset.py first",
              file=sys.stderr)
        return 1
    dataset = json.loads(args.dataset.read_text(encoding="utf-8"))
    if dataset.get("schema_version") != DATASET_SCHEMA:
        print(f"error: {args.dataset} is schema_version "
              f"{dataset.get('schema_version')!r}; this script reads "
              f"{DATASET_SCHEMA}. Re-run build_dataset.py.", file=sys.stderr)
        return 1

    unexpected = sorted({f["unit_key"] for f in dataset["findings"]
                         if f["severity"] == "blocker" and f["unit_key"]}
                        - {u["key"] for u in dataset["units"] if u["blocked"]})
    if unexpected:
        print("error: dataset carries blocker findings on units that are not "
              "hand-blocked:\n  " + "\n  ".join(unexpected), file=sys.stderr)
        return 1

    batch = build_batch(dataset, args.batch_id)
    out_dir = args.staging_root / args.batch_id
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "proposal.yaml"

    body = yaml.safe_dump(batch, allow_unicode=True, sort_keys=False,
                          default_flow_style=False, width=100)
    path.write_text(HEADER.format(dataset=args.dataset.as_posix(),
                                  n=len(batch["proposals"])) + body,
                    encoding="utf-8")

    print(f"{len(batch['proposals'])} proposals -> {path}")
    print(f"next: python -m cbdb_agent validate --staging {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
