# -*- coding: utf-8 -*-
"""Turn dataset.json into the Track B staging batch: the place names themselves.

    python tools/salt-admin/emit_addresses.py \
        --dataset data/salt-admin/dataset.json \
        --batch-id 2026-09-11-salt-addresses

Writes `data/staging/<batch-id>/proposal.yaml` with three kinds of proposal, in
dependency order:

    admin-cat-codes    2   the two categories, if they do not already exist
    addr-codes        55   one per unit per seat period
    addr-belongs-data 57   the hierarchy edges

Until 2026-09-11 none of this could be submitted at all - `/api/v2` had no create
for `ADDR_CODES` and no write path whatsoever for `ADDR_BELONGS_DATA`, which is why
`docs/11` had to ship a hand-run SQL script. That script is now redundant.

Four things make this batch different from an ordinary one:

* **The child rows' primary keys do not exist yet.** `ADDR_BELONGS_DATA`'s key is
  (c_addr_id, c_belongs_to, c_firstyear, c_lastyear) and the first two are
  `ADDR_CODES` ids the server mints on create. They are written as
  `{"ref": "<proposal id>"}` and resolved by `batch_runner` from each create's
  `result.pk`. See `staging.substitute_pk_refs`.
* **Nothing here can be undone.** Code-table `delete` is 403 (API.md 13.3).
  `ADDR_CODES` and `ADMIN_CAT_CODES` at least have a full-row `update`, so a wrong
  value is correctable - but `ADDR_BELONGS_DATA`'s update whitelist is only
  c_source/c_pages/c_notes, so a wrong parent or a wrong year in its key is
  permanent. That is why the whole batch is reviewed before any of it is sent.
* **The server does not dedupe.** Neither `ADMIN_CAT_CODES` nor `ADDR_CODES` has a
  unique key on its name columns, so a second run makes a second set. BOTH are
  therefore checked live before anything is emitted, by two different routes
  (`tools/salt-admin/live_state.py`), and the result of each check is written into
  the batch - so the human who signs the rows is signing the evidence for them.
  There is no flag to skip this.
* **The generator will not overwrite its own output.** A `proposal.yaml` that
  already exists may carry signatures; a batch id that already appears under
  `data/processed/` has already been submitted. Both refuse rather than silently
  producing a pristine, unsigned file that looks ready to send again.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "src"))

try:
    import yaml
except ImportError as exc:  # pragma: no cover
    raise ImportError("PyYAML is required (see requirements.txt)") from exc

import salt_data as SD  # noqa: E402

DATASET_SCHEMA = 2

CATEGORY_PROPOSALS = {
    "運司": dict(id="cat-yunsi", py="Duzhuanyunyanshisi", hz="都轉運鹽使司",
                trans="Salt Distribution Commission"),
    "分司": dict(id="cat-fensi", py="Fensi", hz="分司",
                trans="Salt Distribution Branch Office"),
}

HEADER = """\
# Ming/Qing salt administration - Track B: the place names.
#
# Generated by tools/salt-admin/emit_addresses.py from {dataset}.
# Design: docs/11-salt-administration-design.md
#
# {n} proposals: {ncat} category codes, {naddr} ADDR_CODES rows, {nedge}
# ADDR_BELONGS_DATA edges. Submitted in that order - the edges' primary keys are
# made of ids the server assigns to the address creates, carried here as
# `{{ref: <proposal id>}}` and substituted at submit time.
#
# EVERY proposal is approval-gated (AGENTS.md rule 12) and `validate` refuses the
# batch until a named human replaces each `approved_by: null`. The agent must not
# fill those in.
#
# NOTHING HERE CAN BE DELETED. Code-table delete is 403 (API.md 13.3). ADDR_CODES
# and ADMIN_CAT_CODES can at least be corrected by a later update; an
# ADDR_BELONGS_DATA row's four-column key cannot be changed or removed at all.
#
# After a successful load, the derived ADDRESSES cache must be rebuilt or these
# places stay invisible to posting autofill and dynasty homonym disambiguation:
#     php artisan cbdb:regenerate-addresses-table
"""


def addr_proposal_id(key: str) -> str:
    """`salt:ming:兩淮:泰州分司@1368` -> a short, unique, readable proposal id."""
    return "addr-" + key.removeprefix("salt:").replace(":", "-").replace("@", "-")


def edge_proposal_id(child_key: str, n: int) -> str:
    return f"edge-{addr_proposal_id(child_key).removeprefix('addr-')}-{n}"


def parent_label(parent_name: str) -> str:
    """The parent as a human reads it, not as the generator keys it.

    A 分司's parent is one seat-period row of its 運司, and the dataset
    disambiguates those with `運司@治所` - a key, not a name. Writing that straight
    into `c_notes` put `兩淮都轉運鹽使司@揚州府` into 43 rows of global reference
    data. The seat is worth keeping (it is what distinguishes the parent rows from
    each other); the `@` is not.
    """
    name, sep, seat = str(parent_name or "").partition("@")
    return f"{name}（治{seat}）" if sep and seat else name


def edge_note(parent_name: str) -> str:
    """`c_notes` for a hierarchy edge: which parent, and on whose authority."""
    return f"隸屬：{parent_label(parent_name)}\n{SD.SOURCE_NOTE}"


def build_batch(dataset: dict, batch_id: str, *, admin_cat_mode: str,
                categories_present: dict[str, int | None],
                evidence: dict | None = None) -> dict:
    """`evidence` is what the two live duplicate checks found.

    Required whenever anything is emitted. Creating a row in a table with no
    dedupe, no unique key and no delete is the one mistake here that cannot be
    taken back, so "is it already there?" must be answered and *recorded*, not
    assumed - and recorded in the batch, because the batch is what gets signed,
    not the terminal the generator ran in.
    """
    units = [u for u in dataset["units"] if u["emitted"]]
    if evidence is None:
        raise ValueError(
            "build_batch needs the live duplicate-check evidence: ADDR_CODES and "
            "ADMIN_CAT_CODES both lack a unique key on their names and neither has "
            "a delete path, so a create must be able to show it is not a duplicate"
        )
    proposals: list[dict] = []

    # --- 1. the two category codes ------------------------------------------
    cat_ref: dict[str, object] = {}
    if admin_cat_mode == "zero":
        cat_ref = {"運司": 0, "分司": 0}
    else:
        cats = evidence["categories"]
        for kind, spec in CATEGORY_PROPOSALS.items():
            existing = categories_present.get(spec["py"])
            if existing is not None:
                # Already there - reuse it rather than minting a synonym. There is
                # no unique key on the name columns, so a second create would
                # simply succeed and split the references between two rows.
                cat_ref[kind] = existing
                continue
            cat_ref[kind] = {"ref": spec["id"]}
            proposals.append({
                "id": spec["id"],
                "resource": "admin-cat-codes",
                "operation": "create",
                "person_id": 0,
                "changes": {
                    "c_admin_cat_py": spec["py"],
                    "c_admin_cat_hz": spec["hz"],
                    "c_admin_cat_trans": spec["trans"],
                    "c_notes": None,
                },
                "source_quote": (
                    f"ADMIN_CAT_CODES has no category for {spec['hz']}; all 362 "
                    f"comparable jurisdiction rows carry a real one and none uses "
                    f"0. Duplicate check: absent as of {cats['as_of']} baseline "
                    f"({cats['baseline_rows']} rows) + {cats['operations_seen']} "
                    f"operations since, run {evidence['checked_at']}."
                ),
                "confidence": "high",
                "approved_by": None,
            })

    # --- 2. the address rows -------------------------------------------------
    for u in units:
        for a in u["addresses"]:
            proposals.append({
                "id": addr_proposal_id(a["key"]),
                "resource": "addr-codes",
                "operation": "create",
                "person_id": 0,
                # no target_pk: c_addr_id is server-assigned
                "changes": {
                    "c_name_chn": u["name"],
                    "c_name": u["romanization"],
                    "c_alt_names": u["name_short"] if u["kind"] == "分司" else None,
                    "c_admin_type": ("Duzhuanyunyanshisi" if u["kind"] == "運司"
                                     else "Fensi"),
                    "c_admin_cat_code": cat_ref[u["kind"]],
                    "c_firstyear": a["first"],
                    "c_lastyear": a["last"],
                    "x_coord": a["x"],
                    "y_coord": a["y"],
                    # Never the seat's CHGIS point: we are borrowing a coordinate,
                    # not claiming to be that place.
                    "CHGIS_PT_ID": None,
                    "c_notes": a["notes"],
                },
                "source_quote": (
                    f"{u['dynasty']}｜{u['name_short']}｜治所 {a['seat']['raw']} "
                    f"{a['first']}–{a['last']}. Duplicate check: no live ADDR_CODES "
                    f"row is named {u['name']} "
                    f"(/api/select/search/addr, {evidence['checked_at']})."
                ),
                "confidence": "high",
                "approved_by": None,
            })

    # --- 3. the hierarchy edges ---------------------------------------------
    for u in units:
        for a in u["addresses"]:
            for n, b in enumerate(a["belongs"], start=1):
                parent = (b["parent_addr_id"] if b["parent_addr_id"] is not None
                          else {"ref": addr_proposal_id(b["parent_key"])})
                label = parent_label(b["parent_name"])
                proposals.append({
                    "id": edge_proposal_id(a["key"], n),
                    "resource": "addr-belongs-data",
                    "operation": "create",
                    "person_id": 0,
                    "target_pk": {
                        "c_addr_id": {"ref": addr_proposal_id(a["key"])},
                        "c_belongs_to": parent,
                        "c_firstyear": b["first"],
                        "c_lastyear": b["last"],
                    },
                    "changes": {
                        "c_source": b["source"],
                        "c_pages": None,
                        "c_notes": edge_note(b["parent_name"]),
                    },
                    "source_quote": f"{u['name_short']} {b['first']}–{b['last']} "
                                    f"隸屬 {label}",
                    "confidence": "high",
                    "approved_by": None,
                })

    ncat = sum(1 for p in proposals if p["resource"] == "admin-cat-codes")
    naddr = sum(1 for p in proposals if p["resource"] == "addr-codes")
    nedge = sum(1 for p in proposals if p["resource"] == "addr-belongs-data")

    excerpt = [
        f"{naddr} place names and {nedge} belongs-to edges for the Ming and Qing "
        f"salt administration, from {dataset['source']['xlsx']} (Ning Hao).",
        "",
        "The office half of this dataset was dropped on 2026-09-11: a separate "
        "import had already covered the salt-administration POST titles, and "
        "Ning Hao's list names the INSTITUTIONS, which belong here as place "
        "names (which was his proposal to begin with).",
    ]
    if ncat:
        excerpt += ["", f"{ncat} ADMIN_CAT_CODES rows are created first; "
                        f"ADDR_CODES.c_admin_cat_code is NOT NULL with an FK."]
    excerpt += ["", *evidence_lines(evidence)]
    blocked = [u for u in dataset["units"] if not u["emitted"]]
    if blocked:
        excerpt += ["", "Excluded pending a decision from Ning Hao:"]
        excerpt += [f"  - {u['dynasty']} {u['name_short']}: "
                    f"{u['blocked_reason'] or 'blocker finding'}" for u in blocked]

    return {"batch_id": batch_id, "source_excerpt": "\n".join(excerpt),
            "proposals": proposals}


def evidence_lines(ev: dict) -> list[str]:
    """How "is this already there?" was answered, for the batch a human signs.

    Both tables, both routes, and the operations actually replayed - not just the
    counts. A signer who cannot see which operations were composed cannot check
    the composition.
    """
    cats = ev["categories"]
    lines = [
        f"Duplicate checks (tools/salt-admin/live_state.py), run {ev['checked_at']}:",
        "",
        "  ADMIN_CAT_CODES - no read endpoint, so the answer is composed:",
        f"    baseline: snapshot of {cats['as_of']} ({cats['age_days']} days old) "
        f"- {cats['baseline_rows']} rows, {cats['baseline_names']} distinct "
        f"c_admin_cat_py",
        f"    plus {cats['operations_seen']} ADMIN_CAT_CODES operations recorded "
        f"since",
    ]
    for py, code in sorted(cats["resolved"].items()):
        lines.append(f"    {py:<22} "
                     + ("exists as " + str(code) if code is not None else "absent"))
    for change in cats.get("changes") or []:
        lines.append(f"    replayed op {change.get('op')} type "
                     f"{change.get('type')} at {change.get('at')} "
                     f"({change.get('c_admin_cat_py')})")
    if not (cats.get("changes") or []):
        lines.append("    (no operations to replay - the baseline stands as-is)")
    lines += [
        "",
        f"  ADDR_CODES - read live: {ev['addresses']['checked']} names queried "
        f"against /api/select/search/addr, matching c_name_chn exactly.",
        f"    {len(ev['addresses']['existing'])} already present.",
    ]
    for name, rows in sorted(ev["addresses"]["existing"].items()):
        lines.append(f"    {name}: {', '.join(str(r.get('c_addr_id')) for r in rows)}")
    return lines


def _refuse_to_clobber(out_dir: Path, processed_root: Path, batch_id: str) -> str | None:
    """Why this batch id must not be (re)generated here, or None if it is safe.

    Two different accidents, both silent:

    * `proposal.yaml` already exists. It may be the file a human has just typed
      114 signatures into; regenerating writes a pristine unsigned one over it.
    * `data/processed/<batch-id>/` exists, which means `submit` has already
      archived this batch. Re-emitting produces a file that looks ready to send
      and would re-create every row that already landed - in tables with no
      delete path. A partially-succeeded batch is the dangerous case, and
      `results.json` in that directory is what says which rows those were.
    """
    processed = processed_root / batch_id
    if processed.exists():
        return (f"{processed.as_posix()} exists - batch {batch_id!r} has already "
                f"been submitted and archived. Read its results.json to see what "
                f"landed; re-emitting the same id would propose creating those "
                f"rows again, in tables with no delete path. Use a new --batch-id "
                f"for whatever is genuinely left to do.")
    path = out_dir / "proposal.yaml"
    if path.exists():
        return (f"{path.as_posix()} already exists. It may carry approvals a human "
                f"has typed in; this script will not write over them. Move or "
                f"delete it deliberately, or pass a different --batch-id.")
    return None


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dataset", type=Path, default=Path("data/salt-admin/dataset.json"))
    ap.add_argument("--batch-id", required=True)
    ap.add_argument("--staging-root", type=Path, default=Path("data/staging"))
    ap.add_argument("--processed-root", type=Path, default=Path("data/processed"))
    ap.add_argument("--admin-cat", choices=("new", "zero"), default=None,
                    help="Default: whatever the dataset was built with. Given "
                         "explicitly it must agree with the dataset, or the review "
                         "page and the batch would disagree about whether two "
                         "category rows are being created.")
    args = ap.parse_args(argv)

    if not args.dataset.exists():
        print(f"error: {args.dataset} not found - run build_dataset.py first",
              file=sys.stderr)
        return 1
    dataset = json.loads(args.dataset.read_text(encoding="utf-8"))
    if dataset.get("schema_version") != DATASET_SCHEMA:
        print(f"error: {args.dataset} is schema_version "
              f"{dataset.get('schema_version')!r}; this script reads {DATASET_SCHEMA}.",
              file=sys.stderr)
        return 1

    dataset_mode = dataset.get("admin_cat_mode", "new")
    if args.admin_cat is None:
        admin_cat = dataset_mode
    elif args.admin_cat != dataset_mode:
        print(f"error: --admin-cat {args.admin_cat} contradicts the dataset, which "
              f"was built with admin_cat_mode {dataset_mode!r}. The review page "
              f"renders the dataset's value, so the two would disagree about "
              f"whether categories are being created. Rebuild the dataset or drop "
              f"the flag.", file=sys.stderr)
        return 1
    else:
        admin_cat = args.admin_cat

    unexpected = sorted({f["unit_key"] for f in dataset["findings"]
                         if f["severity"] == "blocker" and f["unit_key"]}
                        - {u["key"] for u in dataset["units"] if u["blocked"]})
    if unexpected:
        print("error: blocker findings on units that are not hand-blocked:\n  "
              + "\n  ".join(unexpected), file=sys.stderr)
        return 1

    out_dir = args.staging_root / args.batch_id
    refusal = _refuse_to_clobber(out_dir, args.processed_root, args.batch_id)
    if refusal:
        print("error: " + refusal, file=sys.stderr)
        return 1

    import live_state
    from cbdb_agent.audit_log import AuditLog
    from cbdb_agent.config import load_config
    from cbdb_agent.http_client import CbdbApiError, HttpClient
    from cbdb_agent import snapshot as snapmod

    units = [u for u in dataset["units"] if u["emitted"]]
    names = sorted({u["name"] for u in units})
    present: dict[str, int | None] = {}

    client = HttpClient(load_config(), AuditLog(Path("logs")))
    checked_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
    try:
        existing = live_state.find_existing_addresses(client, names)
        cats_evidence: dict = {}
        if admin_cat == "new":
            snap = snapmod.ensure_snapshot(allow_download=False)
            if snap is None:
                print("error: the ADMIN_CAT_CODES duplicate check needs a snapshot "
                      "for its baseline - that table has no read endpoint. Run "
                      "`python -m cbdb_agent snapshot` first.", file=sys.stderr)
                return 1
            state = live_state.resolve_admin_categories(
                client, snap, [c["py"] for c in CATEGORY_PROPOSALS.values()])
            if state["ambiguous"]:
                # Two live rows share the name we were going to reuse. Picking
                # either is a coin flip that permanently decides which synonym 55
                # address rows point at, so a human has to look.
                print("error: the duplicate check found more than one live row for "
                      f"{sorted(state['ambiguous'])}: {state['ambiguous']}. "
                      "Resolve by hand before emitting.", file=sys.stderr)
                return 1
            resolved = {py: (row.get("c_admin_cat_code") if row else None)
                        for py, row in state["found"].items()}
            present = dict(resolved)
            cats_evidence = {
                "as_of": state["as_of"], "age_days": state["age_days"],
                "baseline_rows": state["baseline_rows"],
                "baseline_names": state["baseline_names"],
                "operations_seen": state["operations_seen"],
                "resolved": resolved, "changes": state["changes"],
            }
        else:
            cats_evidence = {
                "as_of": "n/a", "age_days": None, "baseline_rows": 0,
                "baseline_names": 0, "operations_seen": 0, "resolved": {},
                "changes": [],
            }
    except (live_state.LiveStateError, CbdbApiError) as exc:
        print(f"error: the duplicate check could not be completed ({exc}). "
              f"Nothing has been written. These tables have no delete path, so an "
              f"unanswered 'is it already there?' is not a risk worth taking.",
              file=sys.stderr)
        return 1

    if existing:
        print("error: these place names already exist in ADDR_CODES:",
              file=sys.stderr)
        for name, rows in sorted(existing.items()):
            ids = ", ".join(str(r.get("c_addr_id")) for r in rows)
            print(f"  {name}: {ids}", file=sys.stderr)
        print("Creating them again would make permanent duplicates that nothing "
              "can delete, and split the hierarchy between them. Decide per name "
              "whether to reuse the existing row or to distinguish the new one, "
              "then rebuild the dataset.", file=sys.stderr)
        return 1

    evidence = {
        "checked_at": checked_at,
        "categories": cats_evidence,
        "addresses": {"checked": len(names), "existing": existing},
    }
    for line in evidence_lines(evidence):
        print(line)

    batch = build_batch(dataset, args.batch_id, admin_cat_mode=admin_cat,
                        categories_present=present, evidence=evidence)

    # Re-check immediately before writing. The duplicate checks above take a
    # minute or two of rate-limited requests, which is long enough for somebody to
    # start signing the file this is about to overwrite.
    refusal = _refuse_to_clobber(out_dir, args.processed_root, args.batch_id)
    if refusal:
        print("error: " + refusal, file=sys.stderr)
        return 1

    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "proposal.yaml"
    counts = {k: sum(1 for p in batch["proposals"] if p["resource"] == k)
              for k in ("admin-cat-codes", "addr-codes", "addr-belongs-data")}
    body = yaml.safe_dump(batch, allow_unicode=True, sort_keys=False,
                          default_flow_style=False, width=100)
    path.write_text(
        HEADER.format(dataset=args.dataset.as_posix(), n=len(batch["proposals"]),
                      ncat=counts["admin-cat-codes"], naddr=counts["addr-codes"],
                      nedge=counts["addr-belongs-data"]) + body,
        encoding="utf-8")

    print(f"{len(batch['proposals'])} proposals -> {path}")
    for k, v in counts.items():
        print(f"  {k:<20} {v}")
    print("every one needs an approved_by before `validate` will pass it (rule 12)")
    print(f"next: python -m cbdb_agent validate --staging {path.as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
