"""Bridge between a staging batch and the offline review page (tools/review/).

Design (docs/08-review-interface-design.md):

The YAML staging file stays the ONE source of truth and the ONE write path. This
module adds a *round trip* around it, not a second write path:

    proposal.yaml  --export_review_json-->  review.json
                                                 |
                                       tools/review/index.html
                                       (human reviews, decides, edits)
                                                 |
                                            decisions.json
                                                 |
    proposal.yaml  <--apply_decisions----------- +

`review.json` is generated and disposable, exactly like `preview.md` - never
hand-edited, always regenerated by `validate --staging`. `decisions.json` is the
human's output, and `apply_decisions()` is the only thing that reads it. Every
change it makes is reported back as a line the CLI prints, so a human can see what
their clicking actually did before re-validating.

Why a decisions file rather than letting the page write the YAML directly: the page
is a `file://` document with no filesystem write access, and more importantly a
second writer would mean two code paths that can produce a submittable batch. One
writer, one validator, one submitter.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from typing import Any

from .code_lookup import FIELD_CODE_TABLES, LIST_VALUED_FIELDS, code_table_names
from .models import FieldWhitelistError, find_spec_by_alias
from .staging import Issue, ProposalCurrentState, StagingBatch, StagingError

# Bumped when the JSON contract changes in a way the page must know about. The page
# checks it and refuses to load an export it does not understand, rather than
# silently mis-rendering a newer shape.
#   1: initial
#   2: + code_labels / field_code_tables / list_valued_fields (human-readable names
#      for every code, so a reviewer can check `c_office_id: 63057` against what it
#      actually means rather than re-reading the agent's arithmetic)
#   3: + content_hash on every proposal, and on every decision the page exports.
#      Proposal ids and batch ids are both stable across a regeneration, so without
#      it a stored or exported decision re-attached itself to a row whose values
#      had since changed - see proposal_content_hash()
REVIEW_JSON_SCHEMA_VERSION = 3


def proposal_content_hash(proposal: Any) -> str:
    """A fingerprint of everything about a proposal that decides what gets written.

    The review page keeps a reviewer's in-progress decisions in `localStorage`,
    keyed by batch id, so an accidental reload does not lose them. But a batch id is
    chosen by the operator and is stable across regenerations, and a generated
    proposal id (`addr-ming-...-1368`) is derived from the source row and is stable
    too. So re-running the generator after settling an open question produced
    proposals with the SAME ids and DIFFERENT payloads, and the page silently
    re-attached the old decisions - a field edit or a conflict resolution landing on
    a row whose values had changed underneath it. The same hole existed on the
    command line, where a decisions.json from before the regeneration still applied
    cleanly.

    So each proposal carries a hash of its own content; the page stores it with the
    decision and exports it, and both the page and `apply_decisions` refuse a
    decision whose hash no longer matches. Deliberately NOT covered: `source_quote`,
    `confidence` and the issue list - none of them changes what is written, and
    re-deciding because a comment was reworded would be friction with no safety in
    it.
    """
    payload = {
        "resource": proposal.resource,
        "operation": proposal.operation,
        "person_id": proposal.person_id,
        "target_pk": proposal.target_pk or {},
        "changes": proposal.changes or {},
        # The conflicts too - their ids, the field each is about, and the options
        # offered. A `conflict` decision settles which value gets written, and
        # conflict ids are generated (`c1`, `parent`), so a regeneration can reuse
        # one for a different question. Without this, a stored resolution for the
        # old `parent` silently answered the new one. The options' rationales are
        # excluded: rewording one does not change what the choice writes.
        "conflicts": [
            {"id": c.id, "field": c.field,
             "options": [o.value for o in (c.options or [])]}
            for c in (proposal.conflicts or [])
        ],
    }
    blob = json.dumps(payload, sort_keys=True, ensure_ascii=False,
                      separators=(",", ":"))
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()[:16]


# The CBDB table behind each `person_id: 0` resource, for the group heading. Named
# explicitly rather than upper-casing the spec key, because `office` is an aggregate
# over two tables and would otherwise be labelled with a table that does not exist.
GLOBAL_REFERENCE_TABLES = {
    "addr_codes": "ADDR_CODES",
    "addr_belongs_data": "ADDR_BELONGS_DATA",
    "admin_cat_codes": "ADMIN_CAT_CODES",
    "text_codes": "TEXT_CODES",
    "office": "OFFICE_CODES (+ OFFICE_CODE_TYPE_REL)",
}


def export_review_json(
    batch: StagingBatch,
    issues: list[Issue],
    *,
    current_values: dict[str, ProposalCurrentState] | None = None,
    code_labels: dict[str, dict] | None = None,
) -> str:
    """Serialize a batch + its issues + any live current values for the review page.

    Denormalized on purpose: the page gets `person_group`, `unresolved_conflicts`
    and the current-vs-proposed pairing pre-computed, so it never has to re-derive
    validation semantics in JavaScript. Two implementations of "is this conflict
    resolved" would drift, and the Python one is the one that gates submission.
    """
    current_values = current_values or {}
    issues_by_proposal: dict[str, list[Issue]] = {}
    for issue in issues:
        issues_by_proposal.setdefault(issue.proposal_id, []).append(issue)

    # Group sub-resource rows under the person they belong to, so the page can show
    # a person and everything proposed about them together. A proposal's person_id is
    # either "NEW", a sibling proposal's local id, or a real c_personid.
    def group_key(proposal: Any) -> str:
        pid = proposal.person_id
        if isinstance(pid, str) and pid != "NEW":
            return pid  # sibling reference: group under that proposal's id
        if proposal.resource in ("basicinformation", "biogmain", "biog_main"):
            return proposal.id
        if pid == 0:
            # `person_id: 0` is the convention for a row that belongs to NO person -
            # a code-table entry. Grouping those under a group called "0" is not a
            # grouping: a 114-row place-name batch arrived as one undifferentiated
            # accordion. The axis a reviewer actually reads them along is the table,
            # because that is what decides how reversible each row is.
            #
            # Keyed on the spec key, not the resource string: `addr-codes` and
            # `addr_codes` are the same table, and grouping on the raw alias made
            # two groups under one heading.
            try:
                return "table:" + find_spec_by_alias(proposal.resource).key
            except FieldWhitelistError:
                return f"table:{proposal.resource}"
        return str(pid)

    # Label each group with a human-readable name where we can find one, so the page
    # shows 「丁元善」 rather than 「p01」.
    group_labels: dict[str, str] = {}
    for proposal in batch.proposals:
        if proposal.person_id == 0 and proposal.resource not in (
                "basicinformation", "biogmain", "biog_main"):
            try:
                key = find_spec_by_alias(proposal.resource).key
            except FieldWhitelistError:
                key = proposal.resource
            table = GLOBAL_REFERENCE_TABLES.get(key)
            group_labels[group_key(proposal)] = (
                f"{table} - global reference data, belongs to no person"
                if table else
                # Not a known code table. `person_id: 0` on a person sub-resource is
                # a staging mistake, and calling it "global reference data" would
                # endorse it.
                f"{key} - person_id 0, which is not a person"
            )
        if proposal.resource in ("basicinformation", "biogmain", "biog_main"):
            name = proposal.changes.get("c_name_chn")
            label = str(name) if name else f"person {proposal.person_id}"
            if proposal.operation != "create":
                label = f"{label} (#{proposal.person_id})"
            group_labels[group_key(proposal)] = label

    proposals_out = []
    for proposal in batch.proposals:
        content_hash = proposal_content_hash(proposal)
        try:
            spec = find_spec_by_alias(proposal.resource)
            global_reference = spec.is_global_reference_data
            resource_key = spec.key
        except FieldWhitelistError:
            global_reference = False
            resource_key = None

        state = current_values.get(proposal.id)
        fields = []
        for field_name, proposed in proposal.changes.items():
            entry: dict[str, Any] = {"field": field_name, "proposed": proposed}
            if proposal.operation == "create":
                entry["current_status"] = "not_applicable"
            elif state is None:
                entry["current_status"] = "not_fetched"
            elif state.error is not None:
                entry["current_status"] = "fetch_failed"
                entry["current_error"] = state.error
            else:
                entry["current_status"] = "fetched"
                entry["current"] = (state.row or {}).get(field_name)
            fields.append(entry)

        proposals_out.append(
            {
                "id": proposal.id,
                "content_hash": content_hash,
                "resource": proposal.resource,
                "resource_key": resource_key,
                "operation": proposal.operation,
                "person_id": proposal.person_id,
                "target_pk": proposal.target_pk or {},
                "changes": proposal.changes,
                "fields": fields,
                "source_quote": proposal.source_quote,
                "confidence": proposal.confidence,
                "global_reference_data": global_reference,
                "group": group_key(proposal),
                "conflicts": [
                    {
                        "id": c.id,
                        "field": c.field,
                        "description": c.description,
                        "options": [
                            {"value": o.value, "rationale": o.rationale} for o in c.options
                        ],
                        "agent_suggestion": c.agent_suggestion,
                        "agent_reasoning": c.agent_reasoning,
                        "resolution": c.resolution,
                        "resolved": c.resolution is not None,
                    }
                    for c in proposal.conflicts
                ],
                "issues": [
                    {"severity": i.severity, "message": i.message}
                    for i in issues_by_proposal.get(proposal.id, [])
                ],
            }
        )

    payload = {
        "schema_version": REVIEW_JSON_SCHEMA_VERSION,
        "batch_id": batch.batch_id,
        # "<table>:<value>" -> {label, sub?, lines?}. Resolved in Python at export
        # time (code_lookup.py) because the page is opened from file:// and cannot
        # call these endpoints itself. Empty when the export ran offline - the page
        # must stay usable without it.
        "code_labels": code_labels or {},
        # Which code table each field's value belongs to, so the page can look a
        # value up in code_labels without duplicating the mapping in JavaScript.
        "field_code_tables": FIELD_CODE_TABLES,
        "list_valued_fields": sorted(LIST_VALUED_FIELDS),
        # table key -> CBDB table name, so the page can name the table a code was
        # looked for in when it isn't found.
        "code_table_names": code_table_names(),
        "source_excerpt": batch.source_excerpt,
        "batch_notes": batch.batch_notes,
        "group_labels": group_labels,
        "proposals": proposals_out,
        "summary": {
            "proposals": len(batch.proposals),
            "groups": len({p["group"] for p in proposals_out}),
            "errors": sum(1 for i in issues if i.severity == "error"),
            "unresolved_conflicts": sum(
                1 for p in proposals_out for c in p["conflicts"] if not c["resolved"]
            ),
        },
    }
    return json.dumps(payload, ensure_ascii=False, indent=1)


@dataclass
class AppliedChange:
    kind: str  # "resolution" | "field" | "drop"
    proposal_id: str
    detail: str


def _check_reviewed_version(
    raw: dict[str, Any], proposal_id: str, reviewed_hash: dict[str, str]
) -> None:
    """Refuse a decision made about a different version of this proposal.

    A `field` decision rewrites a value and a `conflict` decision settles which
    value is written, so a `decisions.json` produced before the staging file was
    regenerated applies both of those to rows whose payload has since changed.

    Two things keep the guard from firing on legitimate work. The comparison is
    against the hash of the proposal **as it entered apply_decisions**, not as it
    stands mid-loop - a reviewer may make several decisions about one proposal in a
    single pass, and their own earlier edit must not invalidate their later one. And
    it is only consulted when a decision would actually CHANGE something: re-applying a
    decisions file to a staging file it has already been applied to is a no-op, not
    a stale decision, and refusing it would break re-running `apply-review`.
    """
    stamped = raw.get("content_hash")
    current = reviewed_hash.get(proposal_id)
    if stamped == current:
        return
    why = (
        "that decisions file carries no content_hash, so it was exported before "
        "this check existed"
        if stamped is None else
        f"decided against {stamped!r}, this file is {current!r}"
    )
    raise StagingError(
        f"decision for {proposal_id!r} was made about a version of that proposal "
        f"that is not the one in this staging file ({why}). A proposal id survives "
        "a regeneration unchanged, so the decision may have been made about "
        "different values - most likely the staging file was regenerated after the "
        "review. Re-export review.json, look at the rows that changed, and decide "
        "again."
    )


def apply_decisions(batch: StagingBatch, decisions: dict[str, Any]) -> list[AppliedChange]:
    """Apply a decisions.json produced by the review page onto `batch`, in place.

    Deliberately strict: an unknown proposal or conflict id is a StagingError, not a
    silently-skipped line. A decisions file that does not match the batch means one
    of the two has moved on since the export, and quietly applying the half that
    still matches is how a reviewer ends up believing they resolved something they
    did not.

    Returns one AppliedChange per actual modification, so the caller can print
    exactly what happened. A decision that matches the current value is reported as
    no change rather than counted.
    """
    if not isinstance(decisions, dict):
        raise StagingError("decisions file must be a JSON object")

    version = decisions.get("schema_version")
    if version is not None and version != REVIEW_JSON_SCHEMA_VERSION:
        raise StagingError(
            f"decisions file has schema_version {version!r}, but this build speaks "
            f"{REVIEW_JSON_SCHEMA_VERSION}. Re-export review.json and redo the "
            "decisions rather than applying a mismatched file."
        )

    batch_id = decisions.get("batch_id")
    if batch_id is not None and batch_id != batch.batch_id:
        raise StagingError(
            f"decisions file is for batch {batch_id!r} but the staging file is "
            f"{batch.batch_id!r} - refusing to cross-apply."
        )

    by_id = {p.id: p for p in batch.proposals}
    # The hash of each proposal AS REVIEWED, taken before anything is applied.
    #
    # A reviewer may make several decisions about one proposal in a single pass -
    # that is the ordinary use of the page, since every field is editable and every
    # conflict is settled there. They arrive in one file. Recomputing the hash per
    # decision compared each one against a proposal that same file had just changed,
    # and refused the whole file with "re-export and decide again" - which reproduces
    # the failure, because the loop is the reviewer's own edit. What every decision
    # has to be checked against is the version they were shown.
    reviewed_hash = {p.id: proposal_content_hash(p) for p in batch.proposals}
    applied: list[AppliedChange] = []

    for raw in decisions.get("decisions", []):
        proposal_id = raw.get("proposal_id")
        proposal = by_id.get(proposal_id)
        if proposal is None:
            raise StagingError(
                f"decisions file references unknown proposal id {proposal_id!r}"
            )

        if "conflict_id" in raw:
            conflict_id = raw["conflict_id"]
            conflict = next((c for c in proposal.conflicts if c.id == conflict_id), None)
            if conflict is None:
                raise StagingError(
                    f"proposal {proposal_id!r} has no conflict {conflict_id!r}"
                )
            new_value = raw.get("resolution")
            if conflict.resolution != new_value:
                _check_reviewed_version(raw, proposal_id, reviewed_hash)
                conflict.resolution = new_value
                applied.append(
                    AppliedChange(
                        "resolution",
                        proposal_id,
                        f"conflict {conflict_id} resolved as {new_value!r}",
                    )
                )
            continue

        if "field" in raw:
            field_name = raw["field"]
            if raw.get("drop"):
                if field_name in proposal.changes:
                    _check_reviewed_version(raw, proposal_id, reviewed_hash)
                    del proposal.changes[field_name]
                    applied.append(
                        AppliedChange("drop", proposal_id, f"removed field {field_name}")
                    )
                continue
            new_value = raw.get("value")
            if proposal.changes.get(field_name) != new_value:
                _check_reviewed_version(raw, proposal_id, reviewed_hash)
                old = proposal.changes.get(field_name)
                proposal.changes[field_name] = new_value
                applied.append(
                    AppliedChange(
                        "field",
                        proposal_id,
                        f"{field_name}: {old!r} -> {new_value!r}",
                    )
                )
            continue

        raise StagingError(
            f"decision for {proposal_id!r} has neither conflict_id nor field - "
            "don't know what it is asking for"
        )

    return applied
