"""Bridge between a staging batch and the offline review page (tools/review/).

Design (docs/08-review-interface-design.md):

The YAML staging file stays the ONE source of truth and the ONE write path. This
module adds a *round trip* around it, not a second write path:

    proposal.yaml  --export_review_json-->  review.json
                                                 |
                                       tools/review/index.html
                                       (human reviews, decides, edits)
                                                 |
                                            decisions.json
                                                 |
    proposal.yaml  <--apply_decisions----------- +

`review.json` is generated and disposable, exactly like `preview.md` - never
hand-edited, always regenerated by `validate --staging`. `decisions.json` is the
human's output, and `apply_decisions()` is the only thing that reads it. Every
change it makes is reported back as a line the CLI prints, so a human can see what
their clicking actually did before re-validating.

Why a decisions file rather than letting the page write the YAML directly: the page
is a `file://` document with no filesystem write access, and more importantly a
second writer would mean two code paths that can produce a submittable batch. One
writer, one validator, one submitter.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

from .code_lookup import FIELD_CODE_TABLES, LIST_VALUED_FIELDS, code_table_names
from .models import FieldWhitelistError, find_spec_by_alias
from .staging import Issue, ProposalCurrentState, StagingBatch, StagingError

# Bumped when the JSON contract changes in a way the page must know about. The page
# checks it and refuses to load an export it does not understand, rather than
# silently mis-rendering a newer shape.
#   1: initial
#   2: + code_labels / field_code_tables / list_valued_fields (human-readable names
#      for every code, so a reviewer can check `c_office_id: 63057` against what it
#      actually means rather than re-reading the agent's arithmetic)
REVIEW_JSON_SCHEMA_VERSION = 2


def export_review_json(
    batch: StagingBatch,
    issues: list[Issue],
    *,
    current_values: dict[str, ProposalCurrentState] | None = None,
    code_labels: dict[str, dict] | None = None,
) -> str:
    """Serialize a batch + its issues + any live current values for the review page.

    Denormalized on purpose: the page gets `person_group`, `unresolved_conflicts`
    and the current-vs-proposed pairing pre-computed, so it never has to re-derive
    validation semantics in JavaScript. Two implementations of "is this conflict
    resolved" would drift, and the Python one is the one that gates submission.
    """
    current_values = current_values or {}
    issues_by_proposal: dict[str, list[Issue]] = {}
    for issue in issues:
        issues_by_proposal.setdefault(issue.proposal_id, []).append(issue)

    # Group sub-resource rows under the person they belong to, so the page can show
    # a person and everything proposed about them together. A proposal's person_id is
    # either "NEW", a sibling proposal's local id, or a real c_personid.
    def group_key(proposal: Any) -> str:
        pid = proposal.person_id
        if isinstance(pid, str) and pid != "NEW":
            return pid  # sibling reference: group under that proposal's id
        if proposal.resource in ("basicinformation", "biogmain", "biog_main"):
            return proposal.id
        return str(pid)

    # Label each group with a human-readable name where we can find one, so the page
    # shows 「丁元善」 rather than 「p01」.
    group_labels: dict[str, str] = {}
    for proposal in batch.proposals:
        if proposal.resource in ("basicinformation", "biogmain", "biog_main"):
            name = proposal.changes.get("c_name_chn")
            label = str(name) if name else f"person {proposal.person_id}"
            if proposal.operation != "create":
                label = f"{label} (#{proposal.person_id})"
            group_labels[group_key(proposal)] = label

    proposals_out = []
    for proposal in batch.proposals:
        try:
            spec = find_spec_by_alias(proposal.resource)
            needs_approval = spec.requires_explicit_approval
            resource_key = spec.key
        except FieldWhitelistError:
            needs_approval = False
            resource_key = None

        state = current_values.get(proposal.id)
        fields = []
        for field_name, proposed in proposal.changes.items():
            entry: dict[str, Any] = {"field": field_name, "proposed": proposed}
            if proposal.operation == "create":
                entry["current_status"] = "not_applicable"
            elif state is None:
                entry["current_status"] = "not_fetched"
            elif state.error is not None:
                entry["current_status"] = "fetch_failed"
                entry["current_error"] = state.error
            else:
                entry["current_status"] = "fetched"
                entry["current"] = (state.row or {}).get(field_name)
            fields.append(entry)

        proposals_out.append(
            {
                "id": proposal.id,
                "resource": proposal.resource,
                "resource_key": resource_key,
                "operation": proposal.operation,
                "person_id": proposal.person_id,
                "target_pk": proposal.target_pk or {},
                "changes": proposal.changes,
                "fields": fields,
                "source_quote": proposal.source_quote,
                "confidence": proposal.confidence,
                "approved_by": proposal.approved_by,
                "needs_approval": needs_approval,
                "group": group_key(proposal),
                "conflicts": [
                    {
                        "id": c.id,
                        "field": c.field,
                        "description": c.description,
                        "options": [
                            {"value": o.value, "rationale": o.rationale} for o in c.options
                        ],
                        "agent_suggestion": c.agent_suggestion,
                        "agent_reasoning": c.agent_reasoning,
                        "resolution": c.resolution,
                        "resolved": c.resolution is not None,
                    }
                    for c in proposal.conflicts
                ],
                "issues": [
                    {"severity": i.severity, "message": i.message}
                    for i in issues_by_proposal.get(proposal.id, [])
                ],
            }
        )

    payload = {
        "schema_version": REVIEW_JSON_SCHEMA_VERSION,
        "batch_id": batch.batch_id,
        # "<table>:<value>" -> {label, sub?, lines?}. Resolved in Python at export
        # time (code_lookup.py) because the page is opened from file:// and cannot
        # call these endpoints itself. Empty when the export ran offline - the page
        # must stay usable without it.
        "code_labels": code_labels or {},
        # Which code table each field's value belongs to, so the page can look a
        # value up in code_labels without duplicating the mapping in JavaScript.
        "field_code_tables": FIELD_CODE_TABLES,
        "list_valued_fields": sorted(LIST_VALUED_FIELDS),
        # table key -> CBDB table name, so the page can name the table a code was
        # looked for in when it isn't found.
        "code_table_names": code_table_names(),
        "source_excerpt": batch.source_excerpt,
        "batch_notes": batch.batch_notes,
        "group_labels": group_labels,
        "proposals": proposals_out,
        "summary": {
            "proposals": len(batch.proposals),
            "groups": len({p["group"] for p in proposals_out}),
            "errors": sum(1 for i in issues if i.severity == "error"),
            "unresolved_conflicts": sum(
                1 for p in proposals_out for c in p["conflicts"] if not c["resolved"]
            ),
            "missing_approvals": sum(
                1
                for p in proposals_out
                if p["needs_approval"] and not (p["approved_by"] or "").strip()
            ),
        },
    }
    return json.dumps(payload, ensure_ascii=False, indent=1)


@dataclass
class AppliedChange:
    kind: str  # "resolution" | "field" | "approval" | "drop"
    proposal_id: str
    detail: str


def apply_decisions(batch: StagingBatch, decisions: dict[str, Any]) -> list[AppliedChange]:
    """Apply a decisions.json produced by the review page onto `batch`, in place.

    Deliberately strict: an unknown proposal or conflict id is a StagingError, not a
    silently-skipped line. A decisions file that does not match the batch means one
    of the two has moved on since the export, and quietly applying the half that
    still matches is how a reviewer ends up believing they resolved something they
    did not.

    Returns one AppliedChange per actual modification, so the caller can print
    exactly what happened. A decision that matches the current value is reported as
    no change rather than counted.
    """
    if not isinstance(decisions, dict):
        raise StagingError("decisions file must be a JSON object")

    version = decisions.get("schema_version")
    if version is not None and version != REVIEW_JSON_SCHEMA_VERSION:
        raise StagingError(
            f"decisions file has schema_version {version!r}, but this build speaks "
            f"{REVIEW_JSON_SCHEMA_VERSION}. Re-export review.json and redo the "
            "decisions rather than applying a mismatched file."
        )

    batch_id = decisions.get("batch_id")
    if batch_id is not None and batch_id != batch.batch_id:
        raise StagingError(
            f"decisions file is for batch {batch_id!r} but the staging file is "
            f"{batch.batch_id!r} - refusing to cross-apply."
        )

    by_id = {p.id: p for p in batch.proposals}
    applied: list[AppliedChange] = []

    for raw in decisions.get("decisions", []):
        proposal_id = raw.get("proposal_id")
        proposal = by_id.get(proposal_id)
        if proposal is None:
            raise StagingError(
                f"decisions file references unknown proposal id {proposal_id!r}"
            )

        if "conflict_id" in raw:
            conflict_id = raw["conflict_id"]
            conflict = next((c for c in proposal.conflicts if c.id == conflict_id), None)
            if conflict is None:
                raise StagingError(
                    f"proposal {proposal_id!r} has no conflict {conflict_id!r}"
                )
            new_value = raw.get("resolution")
            if conflict.resolution != new_value:
                conflict.resolution = new_value
                applied.append(
                    AppliedChange(
                        "resolution",
                        proposal_id,
                        f"conflict {conflict_id} resolved as {new_value!r}",
                    )
                )
            continue

        if "field" in raw:
            field_name = raw["field"]
            if raw.get("drop"):
                if field_name in proposal.changes:
                    del proposal.changes[field_name]
                    applied.append(
                        AppliedChange("drop", proposal_id, f"removed field {field_name}")
                    )
                continue
            new_value = raw.get("value")
            if proposal.changes.get(field_name) != new_value:
                old = proposal.changes.get(field_name)
                proposal.changes[field_name] = new_value
                applied.append(
                    AppliedChange(
                        "field",
                        proposal_id,
                        f"{field_name}: {old!r} -> {new_value!r}",
                    )
                )
            continue

        if "approved_by" in raw:
            signature = raw["approved_by"]
            if proposal.approved_by != signature:
                proposal.approved_by = signature
                applied.append(
                    AppliedChange(
                        "approval", proposal_id, f"approved_by set to {signature!r}"
                    )
                )
            continue

        raise StagingError(
            f"decision for {proposal_id!r} has none of conflict_id / field / "
            "approved_by - don't know what it is asking for"
        )

    return applied
